### ISSUE TITLE
When pushing messages downtream we are not casting to the correct type

### ISSUE THREAD

**Issue by DonAurelio** [TApplencourt/metababel#108]
`cast_func = @cast_type ? "(#{self.class.instance_variable_get(:@bt_type)})" : '' ` is a dead line. 

https://github.com/TApplencourt/metababel/blob/5999e715532185974ae334607c82f85a02c20a14/lib/metababel/bt2_trace_class_generator.rb#L444-L450

__Possible solution__

* We need to fix this to cast to `@cast_type`, not `@bt_type`.
* In addition, we need to add the special case for struct to const char * (string).

**Comment by DonAurelio** [comment]
Okay, I just realized that we could not cast to the `@cast_type` in get_setter since the user could cast to a non-babeltrace type, then we won't be able to set the field.

**Comment by TApplencourt** [comment]
Yes, push message are more complicated.
In theory, we should have the cast_type as input, and the cast to `bt_type` when calling the function.
For struct -> string , we should do the memcopy trick
