### ISSUE TITLE
Required definition of btx_register_usr_callbacks

### ISSUE THREAD

**Issue by DonAurelio** [TApplencourt/metababel#38]
When doing the filter with no callbacks test, I wanted to write and empty callbacks.c. However, metababel require the user to define `btx_register_usr_callbacks` even if its not used. 

```c
void btx_register_usr_callbacks(void *btx_handle) {
  // Even when we do not have callbacks to register, we need to defined this function.
}
```

**Comment by TApplencourt** [comment]
I will let you think about why we need it :)
