### ISSUE TITLE
Model validation 

### ISSUE THREAD

**Issue by DonAurelio** [TApplencourt/metababel#55]
Seems this validation is not usefull any more.

```ruby
def validate_model(yaml)
  raise "Invalid Model #{yaml}" unless yaml[:stream_classes].all? do |d|
                                         d.key?(:event_common_context_field_class) || d[:event_classes].all? do |d2|
                                           d2.key?(:payload_field_class)
                                         end
                                       end
end
```
This is just validating if the model have `event_common_context_field_class` or fields have `payload_field_class` or both. But we can have models with neither, for instance (below). **Can we remove this validation?**

```yaml
:stream_classes:
- :name: ze
  :event_classes:
  - :name: sched_switch
  - :name: rcu_utilization
  - :name: kmem_kfree
  - :name: event_1
  - :name: event_2
  - :name: event_3
```

Rendering messages like 

```bash
sched_switch: 
rcu_utilization: 
kmem_kfree: 
event_1: 
event_2: 
event_3: 
```

**Comment by TApplencourt** [comment]
I don't know can you find if the babeltrace2 spec said that it's ok to not have any field in the event class?

**Comment by Kerilk** [comment]
> Optional: Payload [field class](https://babeltrace.org/docs/v2.0/libbabeltrace2/group__api-tir-fc.html)
> 
>     Payload field class of the event class.
> 
>     The payload of an event class instance ([event](https://babeltrace.org/docs/v2.0/libbabeltrace2/group__api-tir-ev.html)) contains the event's main data.
> 
>     Use [bt_event_class_set_payload_field_class()](https://babeltrace.org/docs/v2.0/libbabeltrace2/group__api-tir-ev-cls.html#ga983e7a5f556b1ef387135abd84ec5f1b) [bt_event_class_borrow_payload_field_class()](https://babeltrace.org/docs/v2.0/libbabeltrace2/group__api-tir-ev-cls.html#ga3103a61a2a89cffbadc93dd59bc3fd83), and [bt_event_class_borrow_payload_field_class_const()](https://babeltrace.org/docs/v2.0/libbabeltrace2/group__api-tir-ev-

cls.html#ga872b1e195ac988480ecdfc26ad83508e).

**Comment by Kerilk** [comment]
The only thing you can expect is the numeric ID, the rest is optional, even the name. We may want to enforce different rules though.

**Comment by DonAurelio** [comment]
Thanks @Kerilk, so we can remove this validation for now. Are you Ok with that @TApplencourt?

**Comment by TApplencourt** [comment]
Of course! Whatever the spec said :)
