### ISSUE TITLE
Ending comma in metagenerated arguments for functions

### ISSUE THREAD

**Issue by DonAurelio** [TApplencourt/metababel#56]
We did a workaround to deal with leading commas in functions when we do not have common field neither payload fields, by guaranteeing `e` is non-empty, by passing a default variable. But now this approach that is not the best approach since in templates such as  `downstream.c` we do not have a common default variable. In this case we have `bt_event ...` and `void *btx_handle`, as shown below.

```erb
<% downstream_events.each do |e| %>
static void btx_set_message_<%= e.name_sanitized %>(
    bt_event *<%= event_name %>
    <%= e.args.map{ |s| "#{s.type} #{s.name}" }.join(", ") %>) {
  <%= e.body %>
}

void btx_push_message_<%= e.name_sanitized %>(
    void *btx_handle,
    <%= e.args.map{ |s| "#{s.type} #{s.name}" }.join(", ") %>)
```

We should validate if put the ending comma or not in the template like this `<% if not e.args.empty? %>,<% end %>`. **Can we do that?**

```erb
<% downstream_events.each do |e| %>
static void btx_set_message_<%= e.name_sanitized %>(
    bt_event *<%= event_name %><% if not e.args.empty? %>,<% end %>
    <%= e.args.map{ |s| "#{s.type} #{s.name}" }.join(", ") %>) {
  <%= e.body %>
}

void btx_push_message_<%= e.name_sanitized %>(
    void *btx_handle<% if not e.args.empty? %>,<% end %> 
    <%= e.args.map{ |s| "#{s.type} #{s.name}" }.join(", ") %>) {
```

**Comment by TApplencourt** [comment]
Yep! Good idea.

`<%=  "," unless e.args.empty? %>` should work too
