### ISSUE TITLE
Provide accurate value for min

### ISSUE THREAD

**Issue by DonAurelio** [TApplencourt/metababel#6]
When we have an API call that fails every time it is called, the `min` value of our `TallyCoreTime` aggregation class is not updated properly. Then the resulting aggregation ends with an invalid value for min as shown bellow which equal to `std::numeric_limits<uint64_t>::max()`. 

```c
tally:device: { hostname = "iris02", vpid = 1289, vtid = 1098, backend = 0 }, { name = "device_function_name_4", did = 0, sdid = 0, dur = 0, min = 18446744073709551615, max = 0, count = 5, error = 5 }
tally:device: { hostname = "iris02", vpid = 1289, vtid = 1098, backend = 0 }, { name = "device_function_name_3", did = 0, sdid = 0, dur = 0, min = 18446744073709551615, max = 0, count = 5, error = 5 }
```

This error takes place because when there is an error, the value of `min` does not change, that is remains as `std::numeric_limits<uint64_t>::max()`.

```c++
  TallyCoreBase(uint64_t _dur, bool _err) : duration{_dur}, error{_err} {
    count = 1;
    if (!error) {
      min = duration;
      max = duration;
    } else
      duration = 0;
  }
```

Then, during the aggregation and considering we are aggregating (host, pid, tid, backend_id, function_name) and that all these calls failed, in the aggregation operation the `rhs.min` and `this->min` will be the same. An the finalin value for `min` will be `std::numeric_limits<uint64_t>::max()`.

```c++
  TallyCoreBase &operator+=(const TallyCoreBase &rhs) {
    this->duration += rhs.duration;
    this->min = std::min(this->min, rhs.min);
    this->max = std::max(this->max, rhs.max);
    this->count += rhs.count;
    this->error += rhs.error;
    return *this;
  }
```

This only happens when all the occurrences of `(host, pid, tid, backend_id, function_name)` fail, if one of them does not fail, the value will be updated properly.

**Comment by TApplencourt** [comment]
It makes sense; if it fails we just ignore it for the statistic purpose. Indeed, nobody care about the time a function took to fail 

 Maybe we should document this somewhere.

**Comment by DonAurelio** [comment]
This issue is a good place to leave it documented.
