### ISSUE TITLE
`bt_stream_class_get_name` may need to check if the stream support name

### ISSUE THREAD

**Issue by TApplencourt** [TApplencourt/metababel#70]
https://github.com/TApplencourt/metababel/blob/932605d40dc8b202e1beb71ae3da780f8b84d121/template/filter.c.erb#L164C1-L164C78

If you create a `filter` direcltion from a lltng trace, it will segfault. And some stream class doesn't have a name...

**Comment by Kerilk** [comment]
I encountered the issue in real life on JLSE where depending on the context the tally can segfault. As garbage is written for the stream name, your mileage can vary, from segfault to nothing.
