### ISSUE TITLE
Integer renderization in components not complying model

### ISSUE THREAD

**Issue by DonAurelio** [TApplencourt/metababel#81]
Integer renderization is not considering the `field_value_range` defined in the model. The rendered type is always `int64_t` or `uint64_t`, even when the model defines `:field_value_range: 32`.

https://github.com/TApplencourt/metababel/blob/0431f94c842fe1760365774baf24c424cfb6d22d/lib/metababel/bt2_stream_classes_generator.rb#L451

https://github.com/TApplencourt/metababel/blob/0431f94c842fe1760365774baf24c424cfb6d22d/lib/metababel/bt2_stream_classes_generator.rb#L463

A possible solution is to override `@bt_type` to `@bt_type = "int#{@field_value_range}_t"` here 

https://github.com/TApplencourt/metababel/blob/0431f94c842fe1760365774baf24c424cfb6d22d/lib/metababel/bt2_stream_classes_generator.rb#L431

**Comment by TApplencourt** [comment]
`https://babeltrace.org/docs/v2.0/libbabeltrace2/group__api-tir-fc.html#gac32dce95b13939d80a2b20dba31fbdd6`

What append if you put `n == 11` ? `int11_t` doesn't exist.  This is why we have cast-type.

For babeltrace2, it's always `uint64_t`, you just restrict the value you can put inside, but not the type.

**Comment by DonAurelio** [comment]
You are right, it's always `int64`.
